spring.application.name=employee_management_system
server.port=1122
spring.datasource.url=jdbc:mysql://localhost:3306/empdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nithishdbfcfan@gmail.com
spring.mail.password=bnbc yvnh ztdi nhil

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true